## NumPy Exercises for Data Analysis (Python)

In [4]:
import numpy as np
# Import the Iris data keeping the text intact

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris=np.genfromtxt(url,delimiter=",",dtype="object")
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris.shape)


(150, 5)


In [17]:
import numpy as np
# Extract the text column species from the 1D iris imported in previous question.

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris=np.genfromtxt(url, delimiter=',', dtype=None)

species=[row[4] for row in iris]

print(species[:5])

[np.str_('Iris-setosa'), np.str_('Iris-setosa'), np.str_('Iris-setosa'), np.str_('Iris-setosa'), np.str_('Iris-setosa')]


In [4]:
import numpy as np
# Extract the text column species from the 1D iris imported in previous question.

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris=np.genfromtxt(url, delimiter=',', dtype=None,usecols=[0,1,2,3])
sepallength=iris[:,0]
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)


5.843333333333334 5.8 0.8253012917851409


In [12]:
import numpy as np
# Extract the text column species from the 1D iris imported in previous question.

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris=np.genfromtxt(url, delimiter=',', dtype=None,usecols=[0,1,2,3])
sepallength=iris[:,0]
max_value=np.max(sepallength)
min_value=np.min(sepallength)
# output=(sepallength-min_value)/(max_value-min_value)
output=(sepallength-min_value)/np.ptp(sepallength)
print(output)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

In [14]:
def soft_max(x):    
    return np.exp(x-np.max(x))/np.sum(np.exp(x-np.max(x)))

def test_soft_max(x):
    return np.sum(x-np.max(x))
print(test_soft_max([3,5,1]))


-6


In [ ]:
import numpy as np
# Extract the text column species from the 1D iris imported in previous question.

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris=np.genfromtxt(url, delimiter=',', dtype=None,usecols=[0])
print(soft_max(iris))


In [100]:
import numpy as np
# Extract the text column species from the 1D iris imported in previous question.

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris=np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0,1,2,3])
np.random.seed(100)
x=np.random.randint(150,size=20) #array
y=np.random.randint(4,size=20)   #array
iris[x,y]=np.nan

print(np.isnan(iris).sum())
print(np.where(np.isnan(iris)))
print(np.column_stack(np.where(np.isnan(iris))))


20
(array([  8,  14,  24,  24,  34,  53,  58,  60,  66,  67,  79,  87,  94,
        98, 103, 107, 137, 138, 143, 144]), array([1, 0, 2, 3, 0, 1, 1, 3, 3, 2, 0, 0, 1, 1, 3, 3, 1, 3, 3, 3]))
[[  8   1]
 [ 14   0]
 [ 24   2]
 [ 24   3]
 [ 34   0]
 [ 53   1]
 [ 58   1]
 [ 60   3]
 [ 66   3]
 [ 67   2]
 [ 79   0]
 [ 87   0]
 [ 94   1]
 [ 98   1]
 [103   3]
 [107   3]
 [137   1]
 [138   3]
 [143   3]
 [144   3]]


In [98]:
# Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
condition=(iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0)
print(condition)
iris_2d[condition]


[False False False False False False False False False False False  True
 False False False False False False False False False False False False
  True False False False False  True  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False]


array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [69]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.where((iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0))
iris_2d[np.where((iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0))]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])