In [10]:
import numpy as np
# def compute_vector_length(vector):
#     return np.sqrt(np.sum(vector**2))

def compute_vector_length(vector):
    return np.linalg.norm(vector)
print(compute_vector_length(np.array([3,4])))


5.0


In [41]:
# Compute dot product of 2 vectors:
def compute_dot_product(vector1, vector2):
    # return np.dot(vector1,vector2)
    return vector1@vector2
print(compute_dot_product(np.array([0, 1, -1, 2]),np.array([2, 5, 1, 0])))

4


In [42]:
def matrix_multi_vector(matrix, vector):
    return np.dot(matrix,vector)
print(matrix_multi_vector(np.array([[-1, 1, 1], [0, -4, 9]]),np.array([0, 2, 1])))

[3 1]


In [6]:
# Consine Similarity
def compute_cosine(v1, v2):
    v1=v1.flatten().astype(np.float64)
    v2=v2.flatten().astype(np.float64)
    norm_v1=np.linalg.norm(v1)
    norm_v2=np.linalg.norm(v2)
    if norm_v1==0 or norm_v2==0:
        return 0.0
    return np.dot(v1,v2)/(norm_v1*norm_v2)
print(compute_cosine(np.array([1, 2, 3, 4]),np.array([1, 0, 3, 0])))

0.5773502691896257


In [16]:
# Background Subtraction:
import cv2
Ori_Bg=cv2.imread("Img/original_bg.png",1)
Ori_Bg=cv2.resize(Ori_Bg,(678, 381))

Object_Ig=cv2.imread("Img/object_ig.png",1)
Object_Ig=cv2.resize(Object_Ig,(678, 381))

Target_Bg=cv2.imread("Img/target_bg.png",1)
Target_Bg=cv2.resize(Target_Bg,(678, 381))

difference=cv2.absdiff(Object_Ig,Ori_Bg)
_, thresh_img = cv2.threshold(difference, 5, 255, cv2.THRESH_BINARY)

output=np.where(thresh_img==0,Target_Bg,Object_Ig)
cv2.imwrite("Output/output.png",output)

True

In [18]:
arr = np.arange(0, 10)
print(np.where(arr%2==1,-1,arr))

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
# Grayscale the image
import matplotlib.pyplot as plt
dog_img=cv2.imread("Img/dog_image.png",1)
weights = np.array([0.213, 0.715, 0.072])
output=dog_img@weights
# plt.imshow(dog_img)
# plt.imshow(output, cmap='gray')
print(output[0,0])

245.57399999999998


In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("advertising.csv")
data = df.to_numpy()
sales=data[:,-1]
radio=data[:,1]
newspaper=data[:,2]

mean_newspaper = np.mean(newspaper)

# sum_sales=np.sum(np.where(newspaper>mean_newspaper,sales,0))
sum_sales=np.sum(sales[newspaper>mean_newspaper])

max_value=np.max(sales)
count=len(sales[sales>=20])
# print(f"Max: {max_value}")
# print(f"Length: {count}")
print(sum_sales)

1405.1


In [ ]:
# Tìm dòng nào có pattern chi tiêu giống nhất với một dòng nào đó
target=data[10,:3]
features=data[:,:3]
cosine_similarities=np.array([compute_cosine(feature,target) for feature in features])
most_similar_idx = np.argmax(cosine_similarities)
print(most_similar_idx)
print(data[most_similar_idx,:3])
print(target)

10
[66.1  5.8 24.2]
[66.1  5.8 24.2]
